// <auto-generated />
namespace Revolver.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OrdersContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrdersContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201304150018375_OrdersContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
